#include "helldivers.h"
#include <lvgl_images.h>
#include <stddef.h>

const HellDiversBall_t hellDiversBalls[66] = {
    {
        "MG-43机枪",
        "SASWD",
        &img_mg43,
        BALL_CLASS_WEAPON,
    },
    {
        "APW-1反器材步枪",
        "SADWS",
        &img_apw1,
        BALL_CLASS_WEAPON,
    },
    {
        "M-105盟友",
        "SASWWA",
        &img_M105_stalwart,
        BALL_CLASS_WEAPON,
    },
    {
        "EAT-17消耗性反坦克武器",
        "SSAWD",
        &img_eat17,
        BALL_CLASS_WEAPON,
    },
    {
        "GR-8无后座力步枪",
        "SADDA",
        &img_gr8,
        BALL_CLASS_WEAPON,
    },
    {
        "FLAM-40火焰喷射器",
        "",
        &img_flam40,
        BALL_CLASS_WEAPON,
    },
    {
        "AC-8机炮",
        "SASWWD",
        &img_ac8_autocannon,
        BALL_CLASS_WEAPON,
    },
    {
        "MG-206重机枪",
        "SAWSS",
        &img_mg206,
        BALL_CLASS_WEAPON,
    },
    {
        "RL-77空爆火箭弹发射器",
        "SWWAD",
        &img_rl77,
        BALL_CLASS_WEAPON,
    },
    {
        "MLS-4X突击兵",
        "SAWSD",
        &img_mls_4x_commando,
        BALL_CLASS_WEAPON,
    },

    {
        "RS-422磁轨炮",
        "SDSWAD",
        &img_rs422_railgun,
        BALL_CLASS_WEAPON,
    },
    {
        "FAF-14飞矛",
        "",
        &img_faf14_spear,
        BALL_CLASS_WEAPON,
    },
    {
        "Sta-X3 W.A.S.P.发射器",
        "",
        &img_sta_x3_wasp,
        BALL_CLASS_WEAPON,
    },

    /* 轨道加农炮 */
    {
        "轨道加特林火力网",
        "DSAWW",
        &img_orbita_gatling_barrage,
        BALL_CLASS_ORBOTAL,
    },
    {
        "轨道空爆攻击",
        "DDD",
        &img_orbital_airburst_strike,
        BALL_CLASS_ORBOTAL,
    },
    {
        "轨道120MM高爆弹火力网",
        "DDSADS",
        &img_orbital_120,
        BALL_CLASS_ORBOTAL,
    },
    {
        "轨道380MM高爆弹火力网",
        "DSWWASS",
        &img_orbital_380,
        BALL_CLASS_ORBOTAL,
    },
    {
        "轨道游走火力网",
        "DSDSDS",
        &img_orbital_walking_barrage,
        BALL_CLASS_ORBOTAL,
    },
    {
        "轨道激光炮",
        "DSWDS",
        &img_orbital_laser,
        BALL_CLASS_ORBOTAL,
    },
    {
        "轨道凝固汽油弹火力网",
        "DDSADW",
        &img_orbital_napalm_barrage,
        BALL_CLASS_ORBOTAL,
    },
    {
        "轨道炮攻击",
        "",
        &img_orbital_railcannon_strike,
        BALL_CLASS_ORBOTAL,
    },

    /* 机库 */
    {
        "“飞鹰”机枪扫射",
        "WDD",
        &img_eagle_strafing_run,
        BALL_CLASS_HANGAR,
    },
    {
        "“飞鹰”空袭",
        "WDSD",
        &img_eagle_airstrike,
        BALL_CLASS_HANGAR,
    },
    {
        "“飞鹰”集束炸弹攻击",
        "WDSSD",
        &img_eagle_cluster_bomb,
        BALL_CLASS_HANGAR,
    },
    {
        "“飞鹰”凝固汽油弹空袭",
        "WDSW",
        &img_eagle_napalm_airstrike,
        BALL_CLASS_HANGAR,
    },
    {
        "LIFT-850喷射背包",
        "SWWSW",
        &img_jump_pack,
        BALL_CLASS_HANGAR,
    },
    {
        "“飞鹰”烟雾攻击",
        "WDWS",
        &img_eagle_smoke_strike,
        BALL_CLASS_HANGAR,
    },
    {
        "“飞鹰”110MM火箭巢",
        "WDWA",
        &img_eagle_110_rocket,
        BALL_CLASS_HANGAR,
    },
    {
        "“飞鹰”500KG炸弹",
        "WDSSS",
        &img_eagle_500kg,
        BALL_CLASS_HANGAR,
    },
    {
        "M-102快速侦察载具",
        "",
        &img_car,
        BALL_CLASS_HANGAR,
    },

    /* 舰桥 */
    {
        "轨道精确攻击",
        "DDW",
        &img_orbital_recision_strike,
        BALL_CLASS_BRIDGE,
    },
    {
        "轨道毒气攻击",
        "DDSD",
        &img_orbital_gas_strike,
        BALL_CLASS_BRIDGE,
    },
    {
        "轨道电磁冲击波攻击",
        "DWSSD",
        &img_orbital_ems_strike,
        BALL_CLASS_BRIDGE,
    },
    {
        "轨道烟雾攻击",
        "DDSW",
        &img_oribital_smoke_strike,
        BALL_CLASS_BRIDGE,
    },
    {
        "E/MG-101重机枪部署支架",
        "SWADDA",
        &img_hmg_emplacement,
        BALL_CLASS_BRIDGE,
    },
    {
        "FX-12防护罩生成中继器",
        "SSADAD",
        &img_shield_generator,
        BALL_CLASS_BRIDGE,
    },
    {
        "A/ARC-3特斯拉塔",
        "SWDWAD",
        &img_tesla_tower,
        BALL_CLASS_BRIDGE,
    },

    /* 工程港 */
    {
        "MD-6反步兵雷区",
        "SAWD",
        &img_anti_personal_minefield,
        BALL_CLASS_ENGIEERING_BAY,
    },
    {
        "B-1补给背包",
        "",
        &img_supply_pack,
        BALL_CLASS_ENGIEERING_BAY,
    },
    {
        "GL-21榴弹发射器",
        "SAWAS",
        &img_gl21,
        BALL_CLASS_ENGIEERING_BAY,
    },
    {
        "LAS-98激光大炮",
        "",
        &img_las98_laser_cannon,
        BALL_CLASS_ENGIEERING_BAY,
    },
    {
        "MD-I4燃烧地雷",
        "SAAS",
        &img_incendiary_mines,
        BALL_CLASS_ENGIEERING_BAY,
    },
    {
        "AX/LSA-5“护卫犬”漫游车",
        "",
        &img_laser_dog,
        BALL_CLASS_ENGIEERING_BAY,

    },

    {
        "SH-20防弹护盾背包",
        "SAWWD",
        &img_sh20_shield,
        BALL_CLASS_ENGIEERING_BAY,
    },
    {
        "ARC-3电弧发射器",
        "SDSWAA",
        &img_arc3,
        BALL_CLASS_ENGIEERING_BAY,
    },
    {
        "MD-17反坦克地雷",
        "SAWW",
        &img_anti_tank_mines,
        BALL_CLASS_ENGIEERING_BAY,
    },
    {
        "LAS-99类星体加农炮",
        "SSWAD",
        &img_eagle_smoke_strike,
        BALL_CLASS_ENGIEERING_BAY,
    },
    {
        "SH-32防护罩生成包",
        "",
        &img_sh32_shield,
        BALL_CLASS_ENGIEERING_BAY,
    },

    /* 机械工坊 */
    {
        "A/MG-43哨戒机枪",
        "SWDDW",
        &img_machine_gun_sentry,
        BALL_CLASS_ROBOTICS_WORKSHOP,
    },
    {
        "A/G-16加特林哨戒炮",
        "SWDA",
        &img_galting_sentry,
        BALL_CLASS_ROBOTICS_WORKSHOP,
    },
    {
        "A/M-12迫击哨戒炮",
        "SWDDS",
        &img_motrar_sentry,
        BALL_CLASS_ROBOTICS_WORKSHOP,
    },
    {
        "AX/AR-23“护卫犬”",
        "SWAWDS",
        &img_guard_dog,
        BALL_CLASS_ROBOTICS_WORKSHOP,
    },
    {
        "A/MLS-4X火箭哨戒炮",
        "SWDDA",
        &img_rocket_sentry,
        BALL_CLASS_ROBOTICS_WORKSHOP,
    },
    {
        "A/AC-8自动哨戒炮",
        "SWDWAW",
        &img_auto_cannon_sentry,
        BALL_CLASS_ROBOTICS_WORKSHOP,
    },
    {
        "A/M-23电磁冲击波迫击哨戒炮",
        "SWDSD",
        &img_ems_sentry,
        BALL_CLASS_ROBOTICS_WORKSHOP,
    },
    {
        "EXO-45“爱国者”外骨骼装甲",
        "ASDWASS",
        &img_exo45,
        BALL_CLASS_ROBOTICS_WORKSHOP,
    },
    {
        "EXO-49“解放者”外骨骼装甲",
        "ASDWASW",
        &img_exo49,
        BALL_CLASS_ROBOTICS_WORKSHOP,
    },
    /* 化学专家 */

    /* 都市传奇 */
    {
        "SH-51定向护盾",
        "",
        &img_sh51_shield,
        BALL_CLASS_URBAN_LEGENDS,
    },
    {
        "A/FLAM-40火焰喷射哨戒炮",
        "SWDSWW",
        &img_fire_sentry,
        BALL_CLASS_URBAN_LEGENDS,
    },
    {
        "E/AT-12反坦克炮台",
        "SWADDD",
        &img_anti_tank_emplacement,
        BALL_CLASS_URBAN_LEGENDS,
    },

    /* 其他 */
    {
        "重新武装“飞鹰”",
        "WWAWD",
        &img_eagle_reload,
        BALL_CLASS_OTHER,
    },
    {
        "请求增援",
        "SWDAW",
        &img_help,
        BALL_CLASS_OTHER,
    },
    {
        "S.O.S.求救信标",
        "WSDW",
        &img_sos,
        BALL_CLASS_OTHER,
    },
    {
        "重新补给",
        "SSWD",
        &img_supply,
        BALL_CLASS_OTHER,
    },
    {
        "地狱火炸弹",
        "SWASWDSW",
        &img_hell_boom,
        BALL_CLASS_OTHER,
    },
    {NULL, NULL, NULL, BALL_CLASS_NONE},
};
